logging:
  level:
    root: DEBUG
    org.springframework: WARN
    com.baomidou.mybatisplus: DEBUG
    org.springframework.cloud: DEBUG

server:
  port: 8080
  tomcat:
    apr:
      enabled: false

spring:
  profiles:
    active: dev
  application:
    name: user-service

jwt:
  login-type: app
  secret-key: third_games_secret
  timeout: 86400
