spring:
  cloud:
    nacos:
      username: nacos      # 默认用户名
      password: 123456     # 默认密码
      discovery:
        server-addr: 192.168.10.138:8848  # Nacos server address
        service: ${spring.application.name}  # 服务名
        group: DEFAULT_GROUP         # 服务组
        cluster-name: default        # 集群名
        namespace: public           # Nacos命名空间
