spring:
  cloud:
    nacos:
      username: nacos      # 默认用户名
      password: 123456      # 默认密码
      config:
        server-addr: 192.168.10.138:8848  # Nacos server address
        file-extension: yml          # File type (json, yaml, etc.)
        name: test       # Config file name in Nacos
        namespace: public
      discovery:
        server-addr: 192.168.10.138:8848  # Nacos server address
        service: "${spring.application.name}"  # Service name
        group: DEFAULT_GROUP         # Group for service discovery
        cluster-name: default        # Cluster name for service discovery
        namespace: public
