logging:
  level:
    root: WARN
    org.springframework: ERROR
    com.baomidou.mybatisplus: DEBUG

server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: product-service


jwt:
  login-type: app
  secret-key: third_games_secret
  timeout: 86400